# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: requirements.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Define the output formats you need
formats:
  - htmlzip
  - pdf
  - epub

html_theme: 'sphinx_rtd_theme'
html_static_path: ['_static']

# Details of the project
project: 'Data Safari'
copyright: '2024, George Dreemer'
author: 'George Dreemer'
language: None
exclude_patterns: ['_build', 'Thumbs.db', '.DS_Store']
