# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Define the output formats you need
formats:
  - htmlzip
  - pdf
  - epub
