# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox-travis
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script: tox

# Cache to speed up builds
cache: pip

# Setup notifications
notifications:
  email:
    recipients:
      - georgedreemer@proton.me
    on_success: change 
    on_failure: always 